app: sls1-service
org: willydownhouse
service: sls1-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev

  apiGateway:
    apiKeys:
      - my-secret-api-key

  environment:
    DYNAMODB_CUSTOMER_TABLE: ${self:service}-customerTable-${sls:stage}
    STAGE: ${sls:stage}

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:Get*"
            - "dynamodb:Scan*"
            - "dynamodb:UpdateItem"
            - "dynamodb:DeleteItem"
          Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-customerTable-${sls:stage}

functions:
  health:
    handler: src/handler.health
    events:
      - http:
          path: /health
          method: get
          private: true

  createCustomer:
    handler: src/createCustomer.createCustomer
    events:
      - http:
          path: /customers
          method: post
          private: true

  getCustomers:
    handler: src/getCustomers.getCustomers
    events:
      - http:
          path: /customers
          method: get
          private: true

resources:
  Resources:
    CustomerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: primary_key
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: primary_key
            KeyType: HASH
        TableName: ${self:service}-customerTable-${sls:stage}
#https://0876hx9qx8.execute-api.us-east-1.amazonaws.com/dev/customers
