app: sls1-service
org: willydownhouse
service: sls1-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x

  apiGateway:
    apiKeys:
      - my-secret-api-key

    binaryMediaTypes:
      - "multipart/form-data"

  environment:
    DYNAMODB_OBS_TABLE: ${self:service}-obsTable-${sls:stage}
    BUCKET: ${self:service}-obphotosbucket-${sls:stage}
    STAGE: ${sls:stage}
    API_KEY: ${param:my-secret-api-key}

  # these are permissions for all functions
  # plugin serverless-iam-roles-per-function
  iam:
    role:
      name: ${self:service}-myAppRole-${sls:stage}
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:Query"
            - "dynamodb:PutItem"
            - "dynamodb:Get*"
            - "dynamodb:Scan*"
            - "dynamodb:UpdateItem"
            - "dynamodb:DeleteItem"
          Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-obsTable-${sls:stage}

        - Effect: Allow
          Action:
            - "s3:PutObject"
            - "s3:PutObjectAcl"
            - "s3:GetObject"
            - "s3:GetObjectAcl"
            - "s3:DeleteObject"
          Resource: arn:aws:s3:::${self:service}-obphotosbucket-${sls:stage}/*

functions:
  uploader:
    handler: src/photoUpload.photoUpload
    events:
      - http:
          path: /upload
          method: post
          private: true

  health:
    handler: src/health.health
    events:
      - http:
          path: /health
          method: get
          private: true

  createOb:
    handler: src/obsCruds/createOb.createOb
    events:
      - http:
          path: /obs
          method: post
          private: true

  getObs:
    handler: src/obsCruds/getObs.getObs
    events:
      - http:
          path: /obs
          method: get
          private: true

  getOneOb:
    handler: src/obsCruds/getOneOb.getOneOb
    events:
      - http:
          path: /obs/{id}
          method: get
          private: true

  updateOb:
    handler: src/obsCruds/updateOb.updateOb
    events:
      - http:
          path: /obs/{id}
          method: put
          private: true

  deleteOb:
    handler: src/obsCruds/deleteOb.deleteOb
    events:
      - http:
          path: /obs/{id}
          method: delete
          private: true

resources:
  Resources:
    ObsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        TableName: ${self:service}-obsTable-${sls:stage}

    ObPhotosBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-obphotosbucket-${sls:stage}
        #AccessControl: PublicRead

plugins:
  - serverless-offline
