name: Deploy dev branch if not skipped

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      # - name: test
      #   run: npm run test
      # - name: Echo github object
      #   run: echo "${{toJson(github)}}"
      - name: serverless deploy
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, 'skip')}}
        uses: serverless/github-action@v3.1
        with:
          args: deploy --stage dev
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
#
